version: '3.8'

services:
  mini-secure-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mini-secure-app
    ports:
      - "3001:3001"
    restart: always
    networks:
      - monitoring-net

networks:
  monitoring-net:
    external: true
